### ISSUE TITLE
Option to remove country drop down

### ISSUE THREAD

**Issue by Gudnith** [amnestywebsite/humanity-donations#9]
I'm setting this plugin up for Amnesty Iceland is it possible to get a option to remove the country drop down box as it is not needed for local amnesty sites.

**Comment by AmnestyAM** [comment]
@jaymcp I think this is in the theme companion and can be closed right?

**Comment by jaymcp** [comment]
That's correct, @AmnestyAM; the country selection is an extension to Donations provided by the Theme Companion plugin
